/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/scene.gltf
Author: AK STUDIO (https://sketchfab.com/inven2000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-cup-992750b0df674378989fa915b0688ce1
Title: Coffee Cup
*/

import React, { useRef } from "react";
import { useGLTF, Decal, useTexture } from "@react-three/drei";
import { state } from "../store";
import { useSnapshot } from "valtio";
import { useFrame } from "@react-three/fiber";
import { Vector3 } from "three";
import * as Three from "three";

const ANIM_SPEED = 5;

export function Cup(props) {
  const snap = useSnapshot(state);
  const volume = useRef();

  const { nodes, materials } = useGLTF("/models/cup.gltf");
  const typesctipt = useTexture(`cup_logo/ts.png`);
  const react = useTexture(`cup_logo/react.png`);
  const vs = useTexture(`cup_logo/vs.png`);

  const logo =
    snap.logo === "react" ? react : snap.logo === "vs" ? vs : typesctipt;

  useFrame((_state, delta) => {
    const cupVolume = snap.cupVolume * 0.005;
    const targetScale = new Vector3(cupVolume, cupVolume, cupVolume);
    volume.current.scale.lerp(targetScale, delta * ANIM_SPEED);
  });

  materials.DefaultMaterial.color = new Three.Color(snap.color);

  return (
    <group {...props} ref={volume} rotation={[0.1, 0, 0]}>
      <mesh
        geometry={nodes.defaultMaterial.geometry}
        material={materials.DefaultMaterial}
      >
        <Decal
          position={[0, 0.1, 0.4]}
          rotation={[0, 0, 0]}
          scale={0.5}
          map={logo}
          map-anisotropy={16}
        />
      </mesh>
      <mesh
        geometry={nodes.defaultMaterial001.geometry}
        material={materials["DefaultMaterial.001"]}
      />
    </group>
  );
}

useGLTF.preload("/models/cup.gltf");
